name: Run binary
description: Run binary

inputs:
  binary:
    description: Binary to run
    required: true

  artifact:
    description: Artifact to download
    required: false

  runArgs:
    description: Command line arguments passed to the binary
    required: false

  runEnv:
    description: Environment variables to set for the binary
    required: false

runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v6
      if: ${{ inputs.artifact != '' }}
      with:
        name: ${{ inputs.artifact }}

    - name: run binary
      shell: bash
      run: |
        chmod +x ${{ inputs.binary }}
        ${{ inputs.runEnv }} ./${{ inputs.binary }} ${{ inputs.runArgs }}
