name: Run binary
description: Run binary

inputs:
  artifact:
    description: Artifact to download
    required: false

  binary:
    description: Binary to run
    required: true  

  runArgs:
    description: Command line arguments passed to the binary
    required: false

  runEnv:
    description: Environment variables to set for the binary
    required: false

  workdir:
    description: Working directory to run the binary in
    required: false

runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v6
      if: ${{ inputs.artifact != '' }}
      with:
        name: ${{ inputs.artifact }}

    - name: Run binary
      shell: bash
      run: |
        chmod +x ${{ inputs.binary }}

        if [ -n "${{ inputs.workdir }}" ]; then
          cd ${{ inputs.workdir }}
        fi

        echo "Running: ${{ inputs.runEnv }} ${{ inputs.binary }} ${{ inputs.runArgs }}"
        ${{ inputs.runEnv }} ${{ inputs.binary }} ${{ inputs.runArgs }}
