name: Run binary
description: Run binary

inputs:
  artifact:
    description: Artifact to download
    required: false

  binary:
    description: Binary to run
    required: true  

  run-args:
    description: Command line arguments passed to the binary
    required: false

  run-env:
    description: Environment variables to set for the binary
    required: false

  workdir:
    description: Working directory to run the binary in
    required: false

runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v6
      if: ${{ inputs.artifact != '' }}
      with:
        name: ${{ inputs.artifact }}

    - name: Run binary
      shell: bash
      run: |
        if [ -n "${{ inputs.workdir }}" ]; then
          cd ${{ inputs.workdir }}
        fi

        chmod +x ${{ inputs.binary }}

        echo "Running: ${{ inputs.run-env }} ${{ inputs.binary }} ${{ inputs.run-args }}"
        ${{ inputs.run-env }} ${{ inputs.binary }} ${{ inputs.run-args }}
